---
project_name: hello_world
python_version: 3.6
pg_version: 9.5
gunicorn_version: 19.7.1

repo:
  url: "{{ repo_url|default('git@github.com:jbradberry/hello_world.git') }}"
  branch: "{{ repo_branch|default('master') }}"

requirements_file: "{{ source_dir }}/requirements/production.txt"

# app_minions: "{{ groups['web'] | union(groups['worker']) }}"
app_minions: "{{ groups['web'] }}"

nodejs_version: "6.x"
nodejs_install_npm_user: "{{ project_name }}"
nodejs_package_json_path: "{{ source_dir }}"

github_deploy_key: "{{ SECRET_GITHUB_DEPLOY_KEY|default('') }}"
# db_host: per environment
db_name: 'hello_world_{{ env_name }}'
db_user: 'hello_world'
db_password: "{{ SECRET_DB_PASSWORD }}"
secret_key: "{{ SECRET_KEY }}"

unmanaged_users:
  - vagrant
